### ISSUE TITLE
Shards installing the old version of shard

### ISSUE THREAD

**Issue by creadone** [schovi/baked_file_system#29]
Hi!

1. I have shards yml:
```yaml
dependencies:
  baked_file_system:
    github: schovi/baked_file_system
    version: 0.9.6
```
2. test.cr
```crystal
require "baked_file_system"

module Test
  class FileStorage
    extend BakedFileSystem
    bake_folder "./html"
  end
end
```
3. Directory `html` on the same level like `test.cr` with `test.html` 
4. And `crystal -v`
```bash
Crystal 0.25.1 (2018-06-30)

LLVM: 5.0.2
Default target: x86_64-apple-macosx
```

When i run `crystal test.cr` i got the error:
```
in lib/baked_file_system/src/loader/loader.cr:31: undefined method 'stat' for File:Class

        io << "  size:            " << File.stat(path).size << ",\n"
                                            ^~~~
```
In the code i see old version:
![image](https://user-images.githubusercontent.com/990803/42479654-91c052f6-83e2-11e8-8520-de0eaf461bb5.png)

Could you say me how i can update shard for version in master?

**Comment by straight-shoota** [comment]
Replace `version: 0.9.6` with `branch: master`.

@schovi We could use a new release!

**Comment by creadone** [comment]
@straight-shoota, thanks!

**Comment by schovi** [comment]
bump `0.9.8`
