### ISSUE TITLE
0.9.8 needs a release/tag

### ISSUE THREAD

**Issue by woodruffw** [schovi/baked_file_system#30]
I'm guessing that you meant to craft one after https://github.com/schovi/baked_file_system/commit/24dbaf2180b872c0f0fc777b34e3759108959e6e.

Thanks for `baked_file_system`!

**Comment by schovi** [comment]
@woodruffw More like a typo 😱

**Comment by schovi** [comment]
https://github.com/schovi/baked_file_system/commit/9b7de9819f82a578ef8b6858b01c8754a165b399

**Comment by woodruffw** [comment]
Thanks!
