### ISSUE TITLE
Release 0.9.7 isn't tagged properly

### ISSUE THREAD

**Issue by peterhoeg** [schovi/baked_file_system#31]
Still shows 0.9.5 in ```shard.yml``` making it impossible to pin something against 0.9.7.

Instead of simply retagging 0.9.7 I suggest making new release 0.9.7.

**Comment by schovi** [comment]
@peterhoeg I am really confused how to fix this.
Version tagged `0.9.7` has the wrong version in shards and next version `0.9.8` simply don't add anything new and just fixing version in shards.yml to `0.9.7`.

I am was really confused when I did that. Any specific tips?

**Comment by peterhoeg** [comment]
Why not just change the version to 0.9.8 and tag it as 0.9.8? It doesn't matter that there are no code changes.

**Comment by schovi** [comment]
0.9.8 fixed
