### ISSUE TITLE
Needs a new release

### ISSUE THREAD

**Issue by hugopl** [schovi/baked_file_system#44]
Some time this doesn't get a release, so some projects like sidekiq are starting to need to use a specific commit hash on shard dependencies instead of a version number.

**Comment by hugopl** [comment]
Now that Crystal 1.0.0 was released, it needs even more a release.... to avoid the `Shard "baked_file_system" may be incompatible with Crystal 1.0.0` messages on shards update.

**Comment by Sija** [comment]
Can be closed, I guess.
