### ISSUE TITLE
Does not find file which has been baked

### ISSUE THREAD

**Issue by serge-hulne** [schovi/baked_file_system#46]
# code

```
require "baked_file_system"

class FileStorage
  extend BakedFileSystem
  bake_folder "../public"
end

path = "../public/index.html"

begin
  file = FileStorage.get path
  p "content = #{file.gets_to_end}"
rescue BakedFileSystem::NoSuchFileError
  puts "File #{path} is missing"
end
```

# file structure

<img width="338" alt="Screenshot 2023-02-23 at 09 14 43" src="https://user-images.githubusercontent.com/303502/220853799-91ce07d1-304f-4ae4-9dc4-854e761136f2.png">

**Comment by straight-shoota** [comment]
When you're baking a folder, files inside that folder are reachable by their path relative to that folder.
The path in the baked file system would be `/index.html`, not `../public/index.html`.

**Comment by serge-hulne** [comment]
Thank you very much.
